/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
    "/api/v1/health": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Service health */
        get: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description Service is up */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["HealthResponse"];
                    };
                };
            };
        };
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/auth/login": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Authenticate a human user
         * @description Exchanges credentials for an access + refresh token pair. Rate-limited (see D12).
         */
        post: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody: {
                content: {
                    "application/json": components["schemas"]["LoginRequest"];
                };
            };
            responses: {
                /** @description Authentication succeeded */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["TokenPair"];
                    };
                };
                401: components["responses"]["Unauthorized"];
                429: components["responses"]["RateLimited"];
            };
        };
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/auth/refresh": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Rotate a refresh token for a new token pair */
        post: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody: {
                content: {
                    "application/json": components["schemas"]["RefreshRequest"];
                };
            };
            responses: {
                /** @description New token pair issued */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["TokenPair"];
                    };
                };
                401: components["responses"]["Unauthorized"];
            };
        };
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/auth/me": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Return the authenticated user */
        get: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description Current user */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["User"];
                    };
                };
                401: components["responses"]["Unauthorized"];
            };
        };
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/auth/logout": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Invalidate the current refresh token */
        post: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description Logged out */
                204: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content?: never;
                };
                401: components["responses"]["Unauthorized"];
            };
        };
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/documents": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** List documents (paginated, filterable) */
        get: {
            parameters: {
                query?: {
                    status?: components["schemas"]["DocumentStatus"];
                    type?: components["schemas"]["DocumentType"];
                    region?: string;
                    page?: number;
                    size?: number;
                };
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description Paginated list */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["DocumentList"];
                    };
                };
            };
        };
        put?: never;
        /**
         * Ingest a document for OCR processing
         * @description Submits an image/PDF for async processing. Returns 202 with the document id.
         *     Enforced guards (D12): rate limit 60 req/min per key, global daily cap 100 docs/day.
         */
        post: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody: {
                content: {
                    "multipart/form-data": {
                        /**
                         * Format: binary
                         * @description image/jpeg, image/png, image/heic, application/pdf (max 10 MB)
                         */
                        file: string;
                        type: components["schemas"]["DocumentType"];
                        /**
                         * @description ISO 3166-1 alpha-2 region code (defaults to AR)
                         * @default AR
                         */
                        region: string;
                    };
                };
            };
            responses: {
                /** @description Accepted for processing */
                202: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["IngestResponse"];
                    };
                };
                413: components["responses"]["PayloadTooLarge"];
                422: components["responses"]["Unprocessable"];
                429: components["responses"]["RateLimited"];
            };
        };
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/documents/{document_id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Retrieve a document with parsed data and validation result */
        get: {
            parameters: {
                query?: never;
                header?: never;
                path: {
                    document_id: components["parameters"]["DocumentId"];
                };
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description Document found */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["Document"];
                    };
                };
                404: components["responses"]["NotFound"];
            };
        };
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/documents/{document_id}/image": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Download the stored image
         * @description Returns the original image (image/jpeg). Presigned URLs only in production (D12).
         */
        get: {
            parameters: {
                query?: never;
                header?: never;
                path: {
                    document_id: components["parameters"]["DocumentId"];
                };
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description Image bytes */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "image/jpeg": string;
                    };
                };
                404: components["responses"]["NotFound"];
                /** @description Image expired by storage lifecycle */
                410: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["ErrorResponse"];
                    };
                };
            };
        };
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/documents/{document_id}/review": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        /**
         * Record a manual review decision / fix extracted fields
         * @description Human-in-the-loop review (ADMIN/REVIEWER). Updates the manual-fix flag and edited fields.
         */
        patch: {
            parameters: {
                query?: never;
                header?: never;
                path: {
                    document_id: components["parameters"]["DocumentId"];
                };
                cookie?: never;
            };
            requestBody: {
                content: {
                    "application/json": components["schemas"]["ReviewRequest"];
                };
            };
            responses: {
                /** @description Updated document */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["Document"];
                    };
                };
                403: components["responses"]["Forbidden"];
                404: components["responses"]["NotFound"];
            };
        };
        trace?: never;
    };
    "/api/v1/documents/{document_id}/export": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Export a document's extracted data
         * @description Returns a flattened, export-ready representation (JSON; CSV via Accept header).
         */
        get: {
            parameters: {
                query?: never;
                header?: never;
                path: {
                    document_id: components["parameters"]["DocumentId"];
                };
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description Export payload */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["DocumentExport"];
                    };
                };
                404: components["responses"]["NotFound"];
            };
        };
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/review/queue": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * List documents awaiting human review
         * @description Documents flagged for manual review (e.g. VALIDATION_FAILED or manual-fix requested).
         */
        get: {
            parameters: {
                query?: {
                    page?: number;
                    size?: number;
                };
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description Review queue */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["DocumentList"];
                    };
                };
                403: components["responses"]["Forbidden"];
            };
        };
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/api-keys": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** List machine-client API keys */
        get: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description List of API keys */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["ApiKeyList"];
                    };
                };
                403: components["responses"]["Forbidden"];
            };
        };
        put?: never;
        /**
         * Create a machine-client API key
         * @description The raw key is returned once and stored only as a SHA-256 hash.
         */
        post: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody: {
                content: {
                    "application/json": components["schemas"]["ApiKeyCreateRequest"];
                };
            };
            responses: {
                /** @description Created API key (raw key shown once) */
                201: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["ApiKeyCreateResponse"];
                    };
                };
                403: components["responses"]["Forbidden"];
            };
        };
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/api-keys/{prefix}/revoke": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Revoke a machine-client API key */
        post: {
            parameters: {
                query?: never;
                header?: never;
                path: {
                    prefix: string;
                };
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description Revoked */
                204: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content?: never;
                };
                403: components["responses"]["Forbidden"];
                404: components["responses"]["NotFound"];
            };
        };
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/dashboard": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Processing summary for the dashboard */
        get: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description Dashboard summary */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["DashboardSummary"];
                    };
                };
                401: components["responses"]["Unauthorized"];
            };
        };
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
}
export type webhooks = Record<string, never>;
export interface components {
    schemas: {
        /** @enum {string} */
        DocumentType: "invoice" | "ticket" | "payment_receipt";
        /** @enum {string} */
        DocumentStatus: "PENDING" | "OCR_IN_PROGRESS" | "VALIDATING" | "COMPLETED" | "VALIDATION_FAILED" | "OCR_FAILED" | "IMAGE_EXPIRED";
        /** @enum {string} */
        MediaType: "image/jpeg" | "image/png" | "image/heic" | "application/pdf";
        /** @enum {string} */
        UserRole: "ADMIN" | "REVIEWER";
        HealthResponse: {
            /** @enum {string} */
            status: "ok";
            ocr_engine: string;
            storage_pct: number;
        };
        ErrorResponse: {
            detail: string;
        };
        IngestResponse: {
            /** Format: uuid */
            document_id: string;
            status: components["schemas"]["DocumentStatus"];
            image_key: string;
        };
        RecipientData: {
            name?: string | null;
            cuit?: string | null;
            individual_amount?: number | null;
            fields?: {
                [key: string]: string;
            };
        };
        ParsedData: {
            raw_text: string;
            confidence: number;
            /**
             * @description Extracted AFIP/invoice fields. Known keys: total_amount, date, vendor_name,
             *     tipo_comprobante, cuit_emisor, cae, cae_vencimiento, iva, total.
             */
            fields: {
                [key: string]: string;
            };
            recipients?: components["schemas"]["RecipientData"][] | null;
        };
        ValidationError: {
            field: string;
            rule: string;
            message: string;
        };
        ValidationResult: {
            passed: boolean;
            errors: components["schemas"]["ValidationError"][];
            region: string;
            /** Format: date-time */
            validated_at: string;
        };
        Document: {
            /** Format: uuid */
            id: string;
            type: components["schemas"]["DocumentType"];
            region: string;
            status: components["schemas"]["DocumentStatus"];
            media_type: components["schemas"]["MediaType"];
            image_key: string;
            /**
             * Format: uuid
             * @description Owner (human user) — nullable for machine-client submissions (D9).
             */
            user_id?: string | null;
            parsed_data?: components["schemas"]["ParsedData"];
            validation_result?: components["schemas"]["ValidationResult"];
            error_detail?: string | null;
            /** Format: date-time */
            created_at: string;
            /** Format: date-time */
            updated_at: string;
        };
        DocumentList: {
            items: components["schemas"]["Document"][];
            total: number;
            page: number;
            pages: number;
        };
        User: {
            /** Format: uuid */
            id: string;
            username: string;
            role: components["schemas"]["UserRole"];
        };
        LoginRequest: {
            username: string;
            /** Format: password */
            password: string;
        };
        RefreshRequest: {
            refresh_token: string;
        };
        TokenPair: {
            access_token: string;
            refresh_token: string;
            /** @enum {string} */
            token_type: "bearer";
            /** @description Access-token lifetime in seconds. */
            expires_in: number;
        };
        ReviewRequest: {
            /** @enum {string} */
            action: "approve" | "reject" | "request_changes";
            /** @description Corrected extracted fields (manual fix). */
            edited_fields?: {
                [key: string]: string;
            };
            comment?: string | null;
        };
        DocumentExport: {
            /** Format: uuid */
            document_id: string;
            type: components["schemas"]["DocumentType"];
            region: string;
            status: components["schemas"]["DocumentStatus"];
            parsed_data: components["schemas"]["ParsedData"];
            validation_result?: components["schemas"]["ValidationResult"];
        };
        ApiKeyCreateRequest: {
            label?: string | null;
        };
        ApiKeyCreateResponse: {
            key: string;
            prefix: string;
            label?: string | null;
        };
        ApiKeyView: {
            prefix: string;
            label?: string | null;
            /** Format: date-time */
            created_at: string;
            revoked: boolean;
        };
        ApiKeyList: {
            items: components["schemas"]["ApiKeyView"][];
        };
        DashboardSummary: {
            counts: {
                [key: string]: number;
            };
            recent: components["schemas"]["Document"][];
        };
    };
    responses: {
        /** @description Missing/invalid credentials */
        Unauthorized: {
            headers: {
                [name: string]: unknown;
            };
            content: {
                "application/json": components["schemas"]["ErrorResponse"];
            };
        };
        /** @description Insufficient role */
        Forbidden: {
            headers: {
                [name: string]: unknown;
            };
            content: {
                "application/json": components["schemas"]["ErrorResponse"];
            };
        };
        /** @description Resource not found */
        NotFound: {
            headers: {
                [name: string]: unknown;
            };
            content: {
                "application/json": components["schemas"]["ErrorResponse"];
            };
        };
        /** @description File exceeds the size limit */
        PayloadTooLarge: {
            headers: {
                [name: string]: unknown;
            };
            content: {
                "application/json": components["schemas"]["ErrorResponse"];
            };
        };
        /** @description Unsupported media type or invalid input */
        Unprocessable: {
            headers: {
                [name: string]: unknown;
            };
            content: {
                "application/json": components["schemas"]["ErrorResponse"];
            };
        };
        /** @description Rate limit or daily quota exceeded */
        RateLimited: {
            headers: {
                /** @description Seconds until retry */
                "Retry-After"?: number;
                [name: string]: unknown;
            };
            content: {
                "application/json": components["schemas"]["ErrorResponse"];
            };
        };
    };
    parameters: {
        DocumentId: string;
    };
    requestBodies: never;
    headers: never;
    pathItems: never;
}
export type $defs = Record<string, never>;
export type operations = Record<string, never>;
